// tslint:disable:no-namespace

/**
 * Animatable CSS properties
 */
export namespace AnimatableProperties {
  export const All = "all";

  export const BackdropFilter = "backdrop-filter";
  export const Background = "background";
  export const BackgroundColor = "background-color";
  export const BackgroundPosition = "background-position";
  export const BackgroundSize = "background-size";
  export const Border = "border";
  export const BorderBottom = "border-bottom";
  export const BorderBottomColor = "border-bottom-color";
  export const BorderBottomLeftRadius = "border-bottom-left-radius";
  export const BorderBottomRightRadius = "border-bottom-right-radius";
  export const BorderBottomWidth = "border-bottom-width";
  export const BorderColor = "border-color";
  export const BorderLeft = "border-left";
  export const BorderLeftColor = "border-left-color";
  export const BorderLeftWidth = "border-left-width";
  export const BorderRadius = "border-radius";
  export const BorderRight = "border-right";
  export const BorderRightColor = "border-right-color";
  export const BorderRightWidth = "border-right-width";
  export const BorderTop = "border-top";
  export const BorderTopColor = "border-top-color";
  export const BorderTopLeftRadius = "border-top-left-radius";
  export const BorderTopRightRadius = "border-top-right-radius";
  export const BorderTopWidth = "border-top-width";
  export const BorderWidth = "border-width";
  export const Bottom = "bottom";
  export const BoxShadow = "box-shadow";
  export const CaretColor = "caret-color";
  export const Clip = "clip";
  export const ClipPath = "clip-path";
  export const Color = "color";
  export const ColumnCount = "column-count";
  export const ColumnGap = "column-gap";
  export const ColumnRule = "column-rule";
  export const ColumnRuleColor = "column-rule-color";
  export const ColumnRuleWidth = "column-rule-width";
  export const ColumnWidth = "column-width";
  export const Columns = "columns";
  export const Filter = "filter";
  export const Flex = "flex";
  export const FlexBasis = "flex-basis";
  export const FlexGrow = "flex-grow";
  export const FlexShrink = "flex-shrink";
  export const Font = "font";
  export const FontSize = "font-size";
  export const FontSizeAdjust = "font-size-adjust";
  export const FontStretch = "font-stretch";
  export const FontVariationSettings = "font-variation-settings";
  export const FontWeight = "font-weight";
  export const Gap = "gap";
  export const GridColumnGap = "grid-column-gap";
  export const GridGap = "grid-gap";
  export const GridRowGap = "grid-row-gap";
  export const Height = "height";
  export const Inset = "inset";
  export const InsetBlock = "inset-block";
  export const InsetBlockEnd = "inset-block-end";
  export const InsetBlockStart = "inset-block-start";
  export const InsetInline = "inset-inline";
  export const InsetInlineEnd = "inset-inline-end";
  export const InsetInlineStart = "inset-inline-start";
  export const Left = "left";
  export const LetterSpacing = "letter-spacing";
  export const LineClamp = "line-clamp";
  export const LineHeight = "line-height";
  export const Margin = "margin";
  export const MarginBottom = "margin-bottom";
  export const MarginLeft = "margin-left";
  export const MarginRight = "margin-right";
  export const MarginTop = "margin-top";
  export const Mask = "mask";
  export const MaskBorder = "mask-border";
  export const MaskPosition = "mask-position";
  export const MaskSize = "mask-size";
  export const MaxHeight = "max-height";
  export const MaxLines = "max-lines";
  export const MaxWidth = "max-width";
  export const MinHeight = "min-height";
  export const MinWidth = "min-width";
  export const MotionOffset = "motion-offset";
  export const MotionRotation = "motion-rotation";
  export const ObjectPosition = "object-position";
  export const OffsetPosition = "offset-position";
  export const Opacity = "opacity";
  export const Order = "order";
  export const Outline = "outline";
  export const OutlineColor = "outline-color";
  export const OutlineOffset = "outline-offset";
  export const OutlineWidth = "outline-width";
  export const Padding = "padding";
  export const PaddingBottom = "padding-bottom";
  export const PaddingLeft = "padding-left";
  export const PaddingRight = "padding-right";
  export const PaddingTop = "padding-top";
  export const Perspective = "perspective";
  export const PerspectiveOrigin = "perspective-origin";
  export const Right = "right";
  export const Rotate = "rotate";
  export const RowGap = "row-gap";
  export const Scale = "scale";
  export const ScrollMargin = "scroll-margin";
  export const ScrollMarginBlock = "scroll-margin-block";
  export const ScrollMarginBlockEnd = "scroll-margin-block-end";
  export const ScrollMarginBlockStart = "scroll-margin-block-start";
  export const ScrollMarginBottom = "scroll-margin-bottom";
  export const ScrollMarginInline = "scroll-margin-inline";
  export const ScrollMarginInlineEnd = "scroll-margin-inline-end";
  export const ScrollMarginInlineStart = "scroll-margin-inline-start";
  export const ScrollMarginLeft = "scroll-margin-left";
  export const ScrollMarginRight = "scroll-margin-right";
  export const ScrollMarginTop = "scroll-margin-top";
  export const ScrollPadding = "scroll-padding";
  export const ScrollPaddingBlock = "scroll-padding-block";
  export const ScrollPaddingBlockEnd = "scroll-padding-block-end";
  export const ScrollPaddingBlockStart = "scroll-padding-block-start";
  export const ScrollPaddingBottom = "scroll-padding-bottom";
  export const ScrollPaddingInline = "scroll-padding-inline";
  export const ScrollPaddingInlineEnd = "scroll-padding-inline-end";
  export const ScrollPaddingInlineStart = "scroll-padding-inline-start";
  export const ScrollPaddingLeft = "scroll-padding-left";
  export const ScrollPaddingRight = "scroll-padding-right";
  export const ScrollPaddingTop = "scroll-padding-top";
  export const ScrollSnapCoordinate = "scroll-snap-coordinate";
  export const ScrollSnapDestination = "scroll-snap-destination";
  export const ScrollbarColor = "scrollbar-color";
  export const ShapeImageThreshold = "shape-image-threshold";
  export const ShapeMargin = "shape-margin";
  export const ShapeOutside = "shape-outside";
  export const TabSize = "tab-size";
  export const TextDecoration = "text-decoration";
  export const TextDecorationColor = "text-decoration-color";
  export const TextEmphasis = "text-emphasis";
  export const TextEmphasisColor = "text-emphasis-color";
  export const TextIndent = "text-indent";
  export const TextShadow = "text-shadow";
  export const Top = "top";
  export const Transform = "transform";
  export const TransformOrigin = "transform-origin";
  export const Translate = "translate";
  export const VerticalAlign = "vertical-align";
  export const Visibility = "visibility";
  export const Width = "width";
  export const WordSpacing = "word-spacing";
  export const ZIndex = "z-index";
  export const Zoom = "zoom";

  export namespace Prefixed {
    export namespace Moz {
      export const OutlineRadius = "-moz-outline-radius";
      export const OutlineRadiusBottomLeft = "-moz-outline-radius-bottomleft";
      export const OutlineRadiusBottomRight = "-moz-outline-radius-bottomright";
      export const OutlineRadiusTopLeft = "-moz-outline-radius-topleft";
      export const OutlineRadiusTopRight = "-moz-outline-radius-topright";
    }
    export namespace Webkit {
      export const TextFillColor = "-webkit-text-fill-color";
      export const TextStroke = "-webkit-text-stroke";
      export const TextStrokeColor = "-webkit-text-stroke-color";
    }
  }
}

export default AnimatableProperties;
