// tslint:disable:object-literal-sort-keys

export const enum PseudoSelectors {
  // No pseudo selector
  None = "&",
  // Children elements
  children = "& > *",

  // "Advanced" pseudo selectors

  MozDir = ":-moz-dir",
  cueDoubleColon = "::cue",
  slottedDoubleColon = "::slotted",
  dir = ":dir",
  has = ":has",
  host = ":host",
  hostContext = ":host-context",
  is = ":is",
  lang = ":lang",
  not = ":not",
  nthChild = ":nth-child",
  nthLastChild = ":nth-last-child",
  nthLastOfType = ":nth-last-of-type",
  nthOfType = ":nth-of-type",
  where = ":where",

  // "Simple" pseudo selectors

  // Single colon browser-prefixed
  MozAnyLink = ":-moz-any-link",
  MozFullScreen = ":-moz-full-screen",
  MozOnlyWhitespace = ":-moz-only-whitespace",
  MozPlaceholder = ":-moz-placeholder",
  MozReadOnly = ":-moz-read-only",
  MozReadWrite = ":-moz-read-write",
  MsFullscreen = ":-ms-fullscreen",
  MsInputPlaceholder = ":-ms-input-placeholder",
  WebkitAnyLink = ":-webkit-any-link",
  WebkitFullScreen = ":-webkit-full-screen",

  // Double colon browser-prefixed
  MozPlaceholderDoubleColon = "::-moz-placeholder",
  MozProgressBar = "::-moz-progress-bar",
  MozRangeProgress = "::-moz-range-progress",
  MozRangeThumb = "::-moz-range-thumb",
  MozRangeTrack = "::-moz-range-track",
  MozSelection = "::-moz-selection",
  MsBackdrop = "::-ms-backdrop",
  MsBrowse = "::-ms-browse",
  MsCheck = "::-ms-check",
  MsClear = "::-ms-clear",
  MsFill = "::-ms-fill",
  MsFillLower = "::-ms-fill-lower",
  MsFillUpper = "::-ms-fill-upper",
  MsReveal = "::-ms-reveal",
  MsThumb = "::-ms-thumb",
  MsTicksAfter = "::-ms-ticks-after",
  MsTicksBefore = "::-ms-ticks-before",
  MsTooltip = "::-ms-tooltip",
  MsTrack = "::-ms-track",
  MsValue = "::-ms-value",
  WebkitBackdrop = "::-webkit-backdrop",
  WebkitInputPlaceholder = "::-webkit-input-placeholder",
  WebkitProgressBar = "::-webkit-progress-bar",
  WebkitProgressInnerValue = "::-webkit-progress-inner-value",
  WebkitProgressValue = "::-webkit-progress-value",
  WebkitSliderRunnableTrack = "::-webkit-slider-runnable-track",
  WebkitSliderThumb = "::-webkit-slider-thumb",

  // Double colon
  afterDoubleColon = "::after",
  backdrop = "::backdrop",
  beforeDoubleColon = "::before",
  firstLetterDoubleColon = "::first-letter",
  firstLineDoubleColon = "::first-line",
  grammarError = "::grammar-error",
  placeholder = "::placeholder",
  selection = "::selection",
  spellingError = "::spelling-error",

  // Single colon
  active = ":active",
  after = ":after",
  anyLink = ":any-link",
  before = ":before",
  blank = ":blank",
  checked = ":checked",
  default = ":default",
  defined = ":defined",
  disabled = ":disabled",
  empty = ":empty",
  enabled = ":enabled",
  first = ":first",
  firstChild = ":first-child",
  firstLetter = ":first-letter",
  firstLine = ":first-line",
  firstOfType = ":first-of-type",
  focus = ":focus",
  focusWithin = ":focus-within",
  fullscreen = ":fullscreen",
  hover = ":hover",
  inRange = ":in-range",
  indeterminate = ":indeterminate",
  invalid = ":invalid",
  lastChild = ":last-child",
  lastOfType = ":last-of-type",
  left = ":left",
  link = ":link",
  onlyChild = ":only-child",
  onlyOfType = ":only-of-type",
  optional = ":optional",
  outOfRange = ":out-of-range",
  placeholderShown = ":placeholder-shown",
  readOnly = ":read-only",
  readWrite = ":read-write",
  required = ":required",
  right = ":right",
  root = ":root",
  scope = ":scope",
  target = ":target",
  valid = ":valid",
  visited = ":visited",
}
